- CMakeLists.txt
+ Fast rtps dependency updated to 1.8.1
+ Background image reenabled by introducing the macro QT5_ADD_RESOURCES. This cmake builtin macro creates a custom build step that calls Qt resource compiler (RCC).
+ Compiling issues due to the employ of cmake wellknown module GetPrerequisites to track ShapesDemo.exe dependencies. These identified dependencies are later use to copy all necessary binaries into the corresponding install dir.
This method only Works properly if the OS is able to find ALL dependencies (preventing naive users from building the tool from sources). We should change it to profit from Qt and fast cmake config files probably introducing colcon.
> Refs #6109 - Several updates on Shapes Demo 

- types/KeylessShapeTypePubSubTypes.cxx
- types/KeylessShapeTypeTypeObject.cxx
KeylessType included in [this Pull Request](https://github.com/eProsima/ShapesDemo/pull/63) did not properly take into account ROS2 name mangling. 
This Pull Request fixes this.
Signed-off-by: Javier Santiago <javiersantiago@eprosima.com>
> Added ROS2 name mangling to keyless type.

- CMakeLists.txt
Old way to check the fastrtps version  compare strings, and `2.10` string is lower than `2.5` string.
It seems there is no longer necessity to use `eprosima_find_package` so it is removed in favor of cmake `find_package`.
> Fix fastrtps version check in CMakeLists

- forms/participantdialog.ui
- forms/ui/ui_optionsdialog.h
- src/qt/participantdialog.cpp
In the Participant configuration dialog, when the user selects an option different from `TCP LAN Server`, starts the participant and closes the dialog, the ComboBox does not save the selected option, hence, when re-opening the dialog again, it is always showed the default `TCP LAN Server`.
This little PR fixes it.
> [18328] TCP ComboBox saving the user selected option

- forms/participantdialog.ui
- include/eprosimashapesdemo/qt/participantdialog.h
- include/eprosimashapesdemo/shapesdemo/ShapesDemo.h
- src/qt/participantdialog.cpp
- src/shapesdemo/ShapesDemo.cpp
The feature adds a checkbox in shapes demo 'Participant Configuration' windows to enable/disable monitor service. Documentation: https://github.com/eProsima/Shapes-Demo-Docs/pull/72
Merge after:
- https://github.com/eProsima/Fast-DDS/pull/3894
> [20034] Enable-Disable monitor service on shapes demo

- forms/publishdialog.ui
- src/qt/mainwindow.cpp
- src/qt/publishdialog.cpp
- src/qt/subscribedialog.cpp
Add the possibility to configure data representation version in publisher datawriter. 
The subscriber datareader is able to read both representation.
Documentation https://github.com/eProsima/Shapes-Demo-Docs/pull/73
> [20106] Add checkbox to configure data representation

- CMakeLists.txt
Reduce CMake minimum version required for Fast DDS compatibility against RHEL 9.
> [20176] Downgrade cmake version

- types/ShapePubSubTypes.cxx
This PR regenerates the Shape types.
This is needed to introduce the Fast DDS Gen release v3.2.1 changes.
> [20176] Regenerate Fast DDS docs example types due to Gen release v3.2.1

- forms/participantdialog.ui
- include/eprosimashapesdemo/qt/participantdialog.h
- include/eprosimashapesdemo/shapesdemo/ShapesDemo.h
- src/qt/participantdialog.cpp
- src/shapesdemo/ShapesDemo.cpp
Udp sample loss feature. 
To run it: 
- Open a terminal and run ShapesDemo. 
- In Options>Participant Configuration select 'Enable UDP sample loss' and press 'Ok' in the popup window.
- Select 'Activate Monitor Service'.
- Create a publisher.
- Open a new terminal and run ShapesDemo.
- In Options>Participant Configuration select 'Activate Monitor Service'.
- Create a subscriber.
- Open Monitor Service application. You can download it here: http://jenkins.eprosima.com:8080/job/ubuntu-fastdds-monitor-installer/75/
- After setting the application, check the report of the samples lost in the 'Problem' section.
Documentation: https://github.com/eProsima/Shapes-Demo-Docs/pull/77
> Udp sample loss feature 

- forms/participantdialog.ui
- include/eprosimashapesdemo/qt/participantdialog.h
- include/eprosimashapesdemo/shapesdemo/ShapesDemo.h
- src/qt/participantdialog.cpp
- src/shapesdemo/ShapesDemo.cpp
This PR adds a check button to avoid sending type information during discovery. Related PRs:
- Fast DDS: eProsima/Fast-DDS#4291
- Shapes Demo Documentation: eProsima/Shapes-Demo-Docs#89
> [20306] Add an auto fill type information check

- README.md
- forms/participantdialog.ui
- include/eprosimashapesdemo/qt/participantdialog.h
- include/eprosimashapesdemo/shapesdemo/ShapesDemo.h
- src/qt/participantdialog.cpp
- src/qt/publishdialog.cpp
- src/qt/subscribedialog.cpp
- src/shapesdemo/ShapesDemo.cpp
Shapes Demo has never worked in data-sharing mode (because the Shape type contains an `unbounded` string).
This PR removes the data-sharing option as it is never used.
@Mergifyio backport 2.6.x 2.10.x 2.12.x 2.13.x
Related documentation PR: 
* eProsima/Shapes-Demo-Docs#100
> [20410] Remove Data-Sharing option 

- forms/participantdialog.ui
This PR moves the ROS 2 line to its proper position
> [20644] Fix ROS 2 line separator in participant configuration

- types/KeylessShapeType.cxx
- types/KeylessShapeTypePubSubTypes.cxx
- types/KeylessShapeTypeTypeObject.cxx
- types/KeylessShapeTypeTypeObject.h
- types/KeylessShapeTypev1.cxx
- types/KeylessShapeTypev1.h
- types/Shape.cxx
- types/ShapeTypeObject.cxx
- types/ShapeTypeObject.h
- types/Shapev1.cxx
- types/Shapev1.h
This PR updates the ShapesDemo types according to the latest Fast DDS Gen released v3.3.0 version.
> [20495] Regenerate shapes types: Fast DDS Gen v3.3.0

- .github/pull_request_template.md
- .github/workflows/build.yml
- .github/workflows/mirror.yml
- README.md
This PR prepares the 3.0.x-devel branch to become Fast DDS Docs master
Related implementation PR:
* eProsima/Fast-DDS#4723
* Related documentation PR: eProsima/Shapes-Demo-Docs#109 -->
- _N/A_: Applicable backports have been included in the description.
> [20893] Prepare 3.0.x-devel to become master

- types/KeylessShapeTypeTypeObjectSupport.cxx
- types/KeylessShapeTypeTypeObjectSupport.hpp
- types/ShapeTypeObjectSupport.cxx
- types/ShapeTypeObjectSupport.hpp
Regeneration of IDL source code to compile against eprosima/fast-dds#4746
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 
- *N/A* Applicable backports have been included in the description.
> Automatic TypeObject representation registration for DynamicTypes [21057]

- src/shapesdemo/ShapesDemo.cpp
The related implementation PR https://github.com/eProsima/Fast-DDS/pull/4657 makes CDRMessage.h private.
This PR substitutes a CDRMessage private function with a simple operation since it was not strictly necessary to use it. 
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
- N/A Applicable backports have been included in the description.
> [20709] Substitute CDRMessage private function with a simple operation

- src/qt/subscribedialog.cpp
This PR updates the usage of DR qos DataRepresentation according to the changes introduced in:
Related implementation PR:
* eProsima/Fast-DDS#4823
- __N/A__ New feature has been documented/Current behavior is correctly described in the documentation. 
- __N/A__ Applicable backports have been included in the description.
> [21053] Move DR TypeConsistencyEnforcement & DataRepresentation from TypeConsistency to DataReaderQos

- src/shapesdemo/ShapesDemo.cpp
This PR adds CDRMessage_t.h to ShapesDemo to fix a compilation error introduced from the 
related implementation PR:
* eProsima/Fast-DDS#4701
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
- N/A Applicable backports have been included in the description.
> [20817] Add CDRMessage_t header

- .github/workflows/build.yml
This PR uses a token for the setup-ccache action from in the CI, which is behind the CI failures on post steps due to exceeding github API usage rate limits
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x
- _N/A_: Changes do not break current interoperability.
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation.
> [21168] Use token for ccache action

- types/KeylessShapeTypePubSubTypes.cxx
- types/KeylessShapeTypePubSubTypes.h
- types/ShapePubSubTypes.cxx
- types/ShapePubSubTypes.h
This PR adjusts Fast DDS Docs for:
* eProsima/Fast-DDS#4960
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
- _N/A_: Applicable backports have been included in the description.
> [21183] Adjust for `const` qualification of all data related inputs in DataWriter APIs

- .github/workflows/nightly-windows-ci.yml
This PRs removes windows nightly job for branch 2.6.x
- **N/A** CI passes without warnings or errors.
> [21229] Remove windows nightly job for 2.6.x

- .github/workflows/nightly-ubuntu-ci.yml
- .github/workflows/nightly-windows-ci.yml
- .github/workflows/weekly-ubuntu-ci.yml
Ubuntu nightly job was failing due to `os-image`-`os-version` name mismatched, and Windows job was failing too due to `vs.toolset`-`vs-toolset` name mismatched.
This PR fixes it and moves `2.6.x` related job to weekly CI
- **N/A** Changes do not break current interoperability.
- N/A CI passes without warnings or errors.
> [21229] Fix nightly jobs and move 2.6.x to weekly CI

- src/shapesdemo/ShapePublisher.cpp
This PR adapts the code to the RTPS writer APIs refactor. In particular, the rename of `heartbeatPeriod` into `heartbeat_period`.
Related implementation PR:
* eProsima/Fast-DDS#5028
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
- _N/A_ Applicable backports have been included in the description.
> [21137] Account for changes on RTPS writer refactor

- include/eprosimashapesdemo/shapesdemo/ShapesDemo.h
This PR removes unused headers. This change is necessary in order for Shapes Demo build with the changes in https://github.com/eProsima/Fast-DDS/pull/5052 
- __NO__ Changes do not break current interoperability.
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
- _N/A_ Applicable backports have been included in the description.
> [21301] Remove `WriterProxyData` from public APIs

- include/eprosimashapesdemo/shapesdemo/ShapeHistory.h
- include/eprosimashapesdemo/shapesdemo/ShapeInfo.h
- src/qt/publishdialog.cpp
- src/qt/subscribedialog.cpp
- src/shapesdemo/ShapeHistory.cpp
Related implementation PR:
* eProsima/Fast-DDS#5065
- __NO__ Changes do not break current interoperability.
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
- __NO__ Applicable backports have been included in the description.
> [21321] Update references to `Time_t` and `Duration_t`

- CMakeLists.txt
This is required in order to build `ShapesDemo` in `Ubuntu 24.04`. When reading the `versions.pri` file, a line break is inserted at the end of the variable, breaking the following compilation flags if any (for instance, in `Ubuntu 22.04`, there were not any)
@Mergifyio backport 2.14.x
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation.
> [21322] Remove new line character at the end of `SHAPESVERSION` cmake variable

- types/KeylessShapeTypeCdrAux.ipp
- types/KeylessShapeTypePubSubTypes.cxx
- types/ShapeCdrAux.ipp
- types/ShapePubSubTypes.cxx
This PR updates the repo types with the latest changes introduced in the Fast DDS Gen v4.
Interoperability changes is not marked in the checklist as the CDR version has been changed to XCDR2.
- ❌ Changes do not break current interoperability.
> [21368] Regenerate types with Fast DDS-Gen v4

- .github/workflows/reusable-ubuntu-ci.yml
- .github/workflows/reusable-windows-ci.yml
This PR use a new eProsima-CI action to install Qt. This migration has been done in order to reach better scalability setting all the external action in the CI repo, so any change required in the action only needs to be done there.
Related PRs:
- https://github.com/eProsima/eProsima-CI/pull/119
- https://github.com/eProsima/Fast-DDS/pull/5186
**Note**: As part of a CI update, this PR needs to be backported also to 2.6.x.
@Mergifyio backport 2.14.x 2.10.x 2.6.x
- **N/A** Changes do not break current interoperability.
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation.
> [21535] Use eProsima-CI action to install Qt

- types/KeylessShapeTypeCdrAux.hpp
- types/KeylessShapeTypeCdrAux.ipp
- types/KeylessShapeTypePubSubTypes.cxx
- types/KeylessShapeTypeTypeObjectSupport.cxx
This PR regenerates Shapes Demo project types with the Fast DDS Gen bump version v4.0.1
> [21636] Regenerate types with Gen v4.0.1

- types/KeylessShapeTypePubSubTypes.cxx
- types/ShapePubSubTypes.cxx
> [21560] Regenerate types with Fast-DDS-Gen v3.3.1

- types/KeylessShapeTypePubSubTypes.cxx
- types/KeylessShapeTypeTypeObjectSupport.cxx
- types/ShapePubSubTypes.cxx
This PR regenerates types with Fast DDS Gen `v4.0.3`
> [22497] Regenerate types with Fast DDS Gen v4.0.3

- .github/workflows/nightly-windows-ci.yml
- .github/workflows/reusable-windows-ci.yml
- .github/workflows/windows-ci.yml
This PR updates the Windows GitHub Action Runner from `windows-2019` to `windows-2022`. As Visual Studio 2017 build tools (v141) are no longer installed in this new runner, the PR upgrades also to toolsets to use, moving from v141 (VS2017) and v142 (VS2019) to v142 (VS2019) and v143 (VS2022).
@Mergifyio backport 3.2.x 2.14.x
- _N/A_ Changes do not break current interoperability.
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation.
> Remove deprecated windows-2019 runner
